### ISSUE TITLE
Aliases only work for canonical suffixes

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/passyunk#14]
`DEVEREAUX AVE` standardizes to `DEVERAUX AVE`, but `DEVEREAUX AVENUE` does not.

Side note: the correct spelling seems to be `DEVERAUX`, but Google Maps (and presumably USPS) has `DEVEREAUX`.

**Comment by tswanson** [comment]
Something isn't using the latest version of passyunk.   I made `DEVEREAUX`the standard spelling

**Comment by rmx90210** [comment]
@tswanson That might be on the API machine. /cc @mjumbewu
