### ISSUE TITLE
312 BAINBRIDGE ST, PHILADELPHIA, PA 19147 1810

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/passyunk#19]
parses to `312 BAINBRIDGE ST PHILADELPHIA PENNSYLVANIA 19147 1810`

**Comment by rmx90210** [comment]
Similar: `2054 REED ST, PHILADELPHIA, PA 19146, USA` => `2054 REED ST PHILADELPHIA PENNSYLVANIA 19146 USA`

**Comment by tswanson** [comment]
Fix is ready to be tested

**Comment by tswanson** [comment]
Resolved
