### ISSUE TITLE
Suppress XXND ZIP-4s

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/passyunk#36]
Saw the following ZIP for `523 N BROAD ST` in AIS: `19123-32ND`. Unless there's a use case for them, should these types of ZIPs be excluded from the Passyunk results?

**Comment by tswanson** [comment]
AIS needs to be updated with the latest passyunk code.  Realized that I am putting other codes in the zip4 field right now that might need to be removed.

**Comment by Alexander-M-Waldman** [comment]
I'm not seeing any of these any more, so closing.
