### ISSUE TITLE
ST ALBANS

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/passyunk#39]
is standardizing to `SAINT ALBANUS`. Shouldn't this be `SAINT ALBANS`?

![image](https://cloud.githubusercontent.com/assets/1463553/20501569/7320a9c2-b008-11e6-861c-2c1a7f7fe17a.png)

**Comment by tswanson** [comment]
This should be fixed in the current branch to push.  @Alexander-M-Waldman please confirm.

**Comment by Alexander-M-Waldman** [comment]
@tswanson confirmed.
