### ISSUE TITLE
Ranged addresses with single-digit high number don't parse

### ISSUE THREAD

**Issue by mjumbewu** [CityOfPhiladelphia/passyunk#4]
For example, trying to parse `'523-5 N BROAD ST'` will raise an exception:

```
ValueError: Addr range, low > high
```

I understand that "523-5" is invalid from a policy perspective, but users wouldn't. Perhaps we could have some kind of strict mode that would not allow it (or a permissive mode that would).

**Comment by tswanson** [comment]
This is a bug.  Also agree that you should get a return instead of an exception in similar cases

**Comment by tswanson** [comment]
Fixed.  Returns 523-05 N BROAD ST.  Removed most of the `ValueError: Addr range, low > high` exceptions
