### ISSUE TITLE
Some block address formats not recognized

### ISSUE THREAD

**Issue by rmx90210** [CityOfPhiladelphia/passyunk#52]
Passyunk recognizes 1200-1299 MARKET ST as a block, but the following as addresses:

* 1200 BLOCK MARKET ST
* 1200 BLOCK OF MARKET ST
* 1200 BLK MARKET ST

When you query the AIS `/search` endpoint for these addresses they are routed to the `/addresses` endpoint and treated as a single address, instead of being routed to `/block`.

**Comment by tswanson** [comment]
Fixed
