### ISSUE TITLE
Remove Whitespace Before Parsing

### ISSUE THREAD

**Issue by nicholas-fink-phl** [CityOfPhiladelphia/passyunk#73]
Would it possible to implement something like `' '.join([addr_var].split())` to remove excess white space before parsing? Is doesn't seem to currently do this.

**Comment by Alexander-M-Waldman** [comment]
@nicholas-fink-phl Can you give an example of an address with white space that isn't trimmed after parsing?

**Comment by nicholas-fink-phl** [comment]
3926 CONSHOHOCKEN AVE       A

**Comment by Alexander-M-Waldman** [comment]
@nicholas-fink-phl looks like that's been fixed
