### ISSUE TITLE
add additional street aliases

### ISSUE THREAD

**Issue by phaedratinder** [CityOfPhiladelphia/passyunk#82]
These are all from voter addresses that went unmatched, but resolved in when used correction.  

Correct to | Input
MCPHERSON | MC PHERSON
SORENTO RD | SORRENTO RD
DAVINCI DR | DA VINCI DR
SHELLEY RD | SHELLY RD
CHEIRON PL | CHERION PL
RAINEY CT | REANEY CT
MAPLEWOOD MALL | MAPLEWOOD AVE
MARKET ST | MARKET SQ
AYRDALE CRESCENT | AYRDALE CIR
OAK LN | OAK LANE AVE
KELLY DR | BOATHOUSE ROW
KEELY CT | KEELY ST

**Comment by Alexander-M-Waldman** [comment]
I incorporated all of these except for MC PHERSON and MARKET SQ which require some additional research.
